import type { z } from 'zod'
import type { storySchema } from './schema'

/**
 * REPRESENTATIVE CONTENT — not actual Chouinard Studios releases.
 *
 * Titles are genuine public-domain works of the kind AUDIOBOOK-BUSINESS.md
 * describes ("carefully selected public-domain or otherwise licensable works",
 * warm / timeless / uplifting / family-friendly). They stand in so the catalog
 * experience can be designed and reviewed against realistic material.
 *
 * Every destination is `pending`: no platform availability is implied, because
 * none exists yet.
 */
export const storyRecords: z.input<typeof storySchema>[] = [
  {
    slug: 'the-secret-garden',
    title: 'The Secret Garden',
    author: 'Frances Hodgson Burnett',
    origin: 'example',
    state: 'in-progress',
    date: '2026-07-30',
    featured: true,
    featureRank: 1,
    tagline: 'A neglected child, a locked garden, and a house that slowly comes back to life.',
    synopsis: [
      'Mary Lennox arrives at her uncle’s house on the Yorkshire moors sour, solitary and entirely unloved. What she finds there — a walled garden nobody has entered in ten years — changes her, and then changes everyone around her.',
      'It is a book about tending things: soil, health, grief, and a family that had stopped speaking. The performance leans into the Yorkshire voices rather than smoothing them out.',
    ],
    sourceNote: 'Public domain (first published 1911).',
    themes: ['Renewal', 'Nature', 'Found family'],
    audienceNote: 'Ages 8 and up, and adults who first read it as children.',
    narrator: 'Jen Chouinard',
    credits: [
      { role: 'Narration & character work', name: 'Jen Chouinard' },
      { role: 'Recording, editing & mastering', name: 'Andrew Chouinard' },
    ],
    runtimeMinutes: 545,
    collections: ['cozy-classics', 'quiet-courage'],
    preview: { note: 'A sample chapter will be posted when the production is finished.' },
    destinations: [
      { platform: 'audible', status: 'pending' },
      { platform: 'apple-books', status: 'pending' },
      { platform: 'libro-fm', status: 'pending' },
      { platform: 'spotify', status: 'pending' },
    ],
  },
  {
    slug: 'anne-of-green-gables',
    title: 'Anne of Green Gables',
    author: 'L. M. Montgomery',
    origin: 'example',
    state: 'in-progress',
    date: '2026-07-12',
    featured: true,
    featureRank: 2,
    tagline: 'The orphan who talked her way into a home she was never meant to have.',
    synopsis: [
      'Matthew and Marilla Cuthbert send for a boy to help on the farm and are sent Anne Shirley instead — red-haired, relentlessly verbal, and incapable of being what anyone expected.',
      'The comedy is in the talking; the weight is in what happens when a person who has never been wanted is finally kept.',
    ],
    sourceNote: 'Public domain (first published 1908).',
    themes: ['Belonging', 'Humour', 'Coming of age'],
    audienceNote: 'Ages 9 and up; a long-standing favourite with adult listeners.',
    narrator: 'Jen Chouinard',
    credits: [
      { role: 'Narration & character work', name: 'Jen Chouinard' },
      { role: 'Recording, editing & mastering', name: 'Andrew Chouinard' },
    ],
    runtimeMinutes: 615,
    collections: ['cozy-classics'],
    preview: { note: 'A sample chapter will be posted when the production is finished.' },
    destinations: [
      { platform: 'audible', status: 'pending' },
      { platform: 'apple-books', status: 'pending' },
      { platform: 'libro-fm', status: 'pending' },
      { platform: 'chirp', status: 'pending' },
    ],
  },
  {
    slug: 'the-wind-in-the-willows',
    title: 'The Wind in the Willows',
    author: 'Kenneth Grahame',
    origin: 'example',
    state: 'coming-soon',
    date: '2026-06-24',
    featured: true,
    featureRank: 3,
    tagline: 'Messing about in boats, and the friend who cannot be left to ruin himself.',
    synopsis: [
      'Mole, Rat, Badger and the catastrophically enthusiastic Mr Toad, in a riverbank world that is somehow both very English and entirely its own.',
      'A book that rewards distinct voices — Toad in particular is unplayable straight.',
    ],
    sourceNote: 'Public domain (first published 1908).',
    themes: ['Friendship', 'Adventure', 'Read-aloud'],
    audienceNote: 'Ages 6 and up, especially good read aloud.',
    narrator: 'Jen Chouinard',
    credits: [{ role: 'Narration & character work', name: 'Jen Chouinard' }],
    runtimeMinutes: 370,
    collections: ['fireside-tales'],
    destinations: [
      { platform: 'audible', status: 'pending' },
      { platform: 'apple-books', status: 'pending' },
    ],
  },
  {
    slug: 'just-so-stories',
    title: 'Just So Stories',
    author: 'Rudyard Kipling',
    origin: 'example',
    state: 'coming-soon',
    date: '2026-05-19',
    tagline: 'How the whale got his throat, and other explanations of dubious accuracy.',
    synopsis: [
      'Short origin tales written to be spoken, full of repeated phrases and deliberate nonsense rhythm. They were made for the voice long before they were made for the page.',
    ],
    sourceNote: 'Public domain (first published 1902).',
    themes: ['Short works', 'Playful', 'Read-aloud'],
    audienceNote: 'Ages 4 and up.',
    narrator: 'Jen Chouinard',
    credits: [{ role: 'Narration & character work', name: 'Jen Chouinard' }],
    runtimeMinutes: 235,
    collections: ['fireside-tales'],
    destinations: [{ platform: 'audible', status: 'pending' }],
  },
  {
    slug: 'a-little-princess',
    title: 'A Little Princess',
    author: 'Frances Hodgson Burnett',
    origin: 'example',
    state: 'coming-soon',
    date: '2026-04-28',
    tagline: 'What a person is worth when everything has been taken from them.',
    synopsis: [
      'Sara Crewe goes from the richest girl at the seminary to its scullery maid overnight, and decides — stubbornly, and at some cost — to behave well anyway.',
    ],
    sourceNote: 'Public domain (first published 1905).',
    themes: ['Resilience', 'Dignity', 'Imagination'],
    audienceNote: 'Ages 8 and up.',
    narrator: 'Jen Chouinard',
    credits: [{ role: 'Narration & character work', name: 'Jen Chouinard' }],
    runtimeMinutes: 425,
    collections: ['quiet-courage', 'cozy-classics'],
    destinations: [
      { platform: 'audible', status: 'pending' },
      { platform: 'libro-fm', status: 'pending' },
    ],
  },
  {
    slug: 'little-women',
    title: 'Little Women',
    author: 'Louisa May Alcott',
    origin: 'example',
    state: 'coming-soon',
    date: '2026-03-15',
    tagline: 'Four sisters, one difficult winter, and everything that comes after.',
    synopsis: [
      'A long book that earns its length. The March sisters are drawn with enough specificity that listeners argue about them a century and a half later.',
    ],
    sourceNote: 'Public domain (first published 1868).',
    themes: ['Family', 'Ambition', 'Character-driven'],
    audienceNote: 'Ages 12 and up.',
    narrator: 'Jen Chouinard',
    credits: [{ role: 'Narration & character work', name: 'Jen Chouinard' }],
    runtimeMinutes: 1035,
    collections: ['cozy-classics'],
    destinations: [{ platform: 'audible', status: 'pending' }],
  },
  {
    slug: 'persuasion',
    title: 'Persuasion',
    author: 'Jane Austen',
    origin: 'example',
    state: 'coming-soon',
    date: '2026-02-09',
    tagline: 'A second chance, eight years late, conducted almost entirely in glances.',
    synopsis: [
      'Anne Elliot at twenty-seven, quieter than an Austen heroine is usually allowed to be, and the naval captain she was talked out of marrying.',
      'The restraint is the point, which makes it an unusually demanding narration.',
    ],
    sourceNote: 'Public domain (first published 1817).',
    themes: ['Second chances', 'Restraint', 'Romance'],
    audienceNote: 'Adult listeners.',
    narrator: 'Jen Chouinard',
    credits: [{ role: 'Narration & character work', name: 'Jen Chouinard' }],
    runtimeMinutes: 490,
    collections: ['quiet-courage'],
    destinations: [{ platform: 'audible', status: 'pending' }],
  },
]
