/**
 * Studio concept imagery — the public-facing derivatives.
 *
 * Originals live in .team-chouinard/design-references/studio/ and are never
 * served. These entries describe the web derivatives generated by
 * scripts/derive-studio-images.ts.
 *
 * All of it is concept imagery for the environment Chouinard Studios is
 * building toward. It is never presented as documentary photography of a
 * finished room — each page that uses it carries one contextual line saying
 * so, rather than a disclaimer under every image.
 */

export interface StudioImageAsset {
  /** Basename of the derivative files under /images/studio/. */
  basename: string
  /** Generated widths, ascending. */
  widths: number[]
  /** Intrinsic size of the largest derivative — drives the aspect ratio. */
  width: number
  height: number
  alt: string
  /** Original this derives from, for traceability. */
  source: string
}

export const studioImages = {
  roomPiano: {
    basename: 'room-piano',
    widths: [700, 1100],
    width: 1100,
    height: 387,
    alt: 'Concept view of the Chouinard Studios live room: a grand piano beside a walnut control desk, with a drum kit and guitars under warm practical lighting.',
    source: 'studio-concept-01.jpeg',
  },
  roomCeiling: {
    basename: 'room-ceiling',
    widths: [600, 799],
    width: 799,
    height: 430,
    alt: 'Concept view of the live room showing the timber acoustic ceiling and wall treatment above the piano and control desk.',
    source: 'studio-concept-02.jpeg',
  },
  ampDetail: {
    basename: 'amp-detail',
    widths: [600, 900, 1206],
    width: 1206,
    height: 1654,
    alt: 'Concept detail: a burgundy amplifier head and cabinet with a microphone placed close to the grille, guitars on the wall behind.',
    source: 'studio-concept-03.jpeg',
  },
  cornerDetail: {
    basename: 'corner-detail',
    widths: [600, 706],
    width: 706,
    height: 922,
    alt: 'Concept detail: candlelight on a walnut table over a patterned rug, beside an amplifier cabinet and a rack of outboard equipment.',
    source: 'studio-concept-06.jpeg',
  },
} satisfies Record<string, StudioImageAsset>

/**
 * Concept references held for internal design direction only.
 *
 * studio-concept-04 and -05 are amplifier specification boards — product
 * specs, settings and paint codes. Publishing them would turn the site into
 * exactly the gear catalogue BRAND-DIRECTION.md rules out, and would surface
 * third-party product detail the studio has no reason to advertise.
 */
export const internalOnlyReferences = [
  { source: 'studio-concept-04.jpeg', reason: 'Amplifier specification board — gear-catalogue content' },
  { source: 'studio-concept-05.jpeg', reason: 'Amplifier specification board — gear-catalogue content' },
] as const
